/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus-secondary/es')['ElAside']
    ElAvatar: typeof import('element-plus-secondary/es')['ElAvatar']
    ElButton: typeof import('element-plus-secondary/es')['ElButton']
    ElCheckbox: typeof import('element-plus-secondary/es')['ElCheckbox']
    ElContainer: typeof import('element-plus-secondary/es')['ElContainer']
    ElDialog: typeof import('element-plus-secondary/es')['ElDialog']
    ElDivider: typeof import('element-plus-secondary/es')['ElDivider']
    ElDropdown: typeof import('element-plus-secondary/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus-secondary/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus-secondary/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus-secondary/es')['ElFooter']
    ElForm: typeof import('element-plus-secondary/es')['ElForm']
    ElFormItem: typeof import('element-plus-secondary/es')['ElFormItem']
    ElHeader: typeof import('element-plus-secondary/es')['ElHeader']
    ElIcon: typeof import('element-plus-secondary/es')['ElIcon']
    ElInput: typeof import('element-plus-secondary/es')['ElInput']
    ElMain: typeof import('element-plus-secondary/es')['ElMain']
    ElMenu: typeof import('element-plus-secondary/es')['ElMenu']
    ElMenuItem: typeof import('element-plus-secondary/es')['ElMenuItem']
    ElOption: typeof import('element-plus-secondary/es')['ElOption']
    ElPagination: typeof import('element-plus-secondary/es')['ElPagination']
    ElScrollbar: typeof import('element-plus-secondary/es')['ElScrollbar']
    ElSelect: typeof import('element-plus-secondary/es')['ElSelect']
    ElSlider: typeof import('element-plus-secondary/es')['ElSlider']
    ElSwitch: typeof import('element-plus-secondary/es')['ElSwitch']
    ElTable: typeof import('element-plus-secondary/es')['ElTable']
    ElTableColumn: typeof import('element-plus-secondary/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus-secondary/es')['ElTabPane']
    ElTabs: typeof import('element-plus-secondary/es')['ElTabs']
    ElTooltip: typeof import('element-plus-secondary/es')['ElTooltip']
    Icon: typeof import('./src/components/icon-custom/src/Icon.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SinglePage: typeof import('./src/components/layout/SinglePage.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus-secondary/es')['ElLoadingDirective']
  }
}
